version: '1'
services:
    db:
      container_name: twt_db
      image: postgres
      ports:
        - "${POSTGRES_COMPOSE_PORT}"
      volumes:
        - db:/var/lib/postgrsql/data
      env_file:
        - .env
      healthcheck: 
        test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
        interval: 5s
        timeout: 10s
        retries: 5
      restart: on-failure

    fastapi_twt_tools:
        container_name: twt_api
        build: ./
        ports: 
         - "${COMPOSE_PORT}"
        env_file:
         - ./.env
        depends_on: 
          db:
            condition: service_healthy
        restart: unless-stopped
volumes:
  db:
    driver: local
